### ISSUE TITLE
Determinar papéis da equipe

### ISSUE THREAD

**Issue by masmangan** [ggirotto/miniature-telegram#1]

**Comment by ggirotto** [comment]
Guilherme Girotto - Developer & Architect

**Comment by NatanaelKun** [comment]
Natanael Kuniechick - Developer - Teser

**Comment by masmangan** [comment]
Mangan - Analista e Gerente de Projetos

**Comment by EpicIcaro** [comment]
Ícaro Espadim - Analyst
